{
  "language": "python",
  "python": "3.6",
  "install": [
    "pip install -r requirements.txt"
  ],
  "script": [
    "pytest -v --pep8"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
